/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TeamRouteImport } from './routes/team'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsAtlasRouteImport } from './routes/projects.atlas'
import { Route as ProjectsDocsRouteImport } from './routes/projects.docs'
import { Route as ProjectsOpsRouteImport } from './routes/projects.ops'
import { Route as ProjectsVoiceRouteImport } from './routes/projects.voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAtlasRoute = ProjectsAtlasRouteImport.update({
  id: '/projects/atlas',
  path: '/projects/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsDocsRoute = ProjectsDocsRouteImport.update({
  id: '/projects/docs',
  path: '/projects/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsOpsRoute = ProjectsOpsRouteImport.update({
  id: '/projects/ops',
  path: '/projects/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsVoiceRoute = ProjectsVoiceRouteImport.update({
  id: '/projects/voice',
  path: '/projects/voice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/writing': typeof WritingRoute
  '/projects/atlas': typeof ProjectsAtlasRoute
  '/projects/docs': typeof ProjectsDocsRoute
  '/projects/ops': typeof ProjectsOpsRoute
  '/projects/voice': typeof ProjectsVoiceRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/writing': typeof WritingRoute
  '/projects/atlas': typeof ProjectsAtlasRoute
  '/projects/docs': typeof ProjectsDocsRoute
  '/projects/ops': typeof ProjectsOpsRoute
  '/projects/voice': typeof ProjectsVoiceRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/writing': typeof WritingRoute
  '/projects/atlas': typeof ProjectsAtlasRoute
  '/projects/docs': typeof ProjectsDocsRoute
  '/projects/ops': typeof ProjectsOpsRoute
  '/projects/voice': typeof ProjectsVoiceRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/team'
    | '/writing'
    | '/projects/atlas'
    | '/projects/docs'
    | '/projects/ops'
    | '/projects/voice'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/team'
    | '/writing'
    | '/projects/atlas'
    | '/projects/docs'
    | '/projects/ops'
    | '/projects/voice'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/team'
    | '/writing'
    | '/projects/atlas'
    | '/projects/docs'
    | '/projects/ops'
    | '/projects/voice'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  WritingRoute: typeof WritingRoute
  ProjectsAtlasRoute: typeof ProjectsAtlasRoute
  ProjectsDocsRoute: typeof ProjectsDocsRoute
  ProjectsOpsRoute: typeof ProjectsOpsRoute
  ProjectsVoiceRoute: typeof ProjectsVoiceRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/atlas': {
      id: '/projects/atlas'
      path: '/projects/atlas'
      fullPath: '/projects/atlas'
      preLoaderRoute: typeof ProjectsAtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/docs': {
      id: '/projects/docs'
      path: '/projects/docs'
      fullPath: '/projects/docs'
      preLoaderRoute: typeof ProjectsDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/ops': {
      id: '/projects/ops'
      path: '/projects/ops'
      fullPath: '/projects/ops'
      preLoaderRoute: typeof ProjectsOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/voice': {
      id: '/projects/voice'
      path: '/projects/voice'
      fullPath: '/projects/voice'
      preLoaderRoute: typeof ProjectsVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  WritingRoute: WritingRoute,
  ProjectsAtlasRoute: ProjectsAtlasRoute,
  ProjectsDocsRoute: ProjectsDocsRoute,
  ProjectsOpsRoute: ProjectsOpsRoute,
  ProjectsVoiceRoute: ProjectsVoiceRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
